### ISSUE TITLE
missions and runtimes need to be filtered according to cluster selected

### ISSUE THREAD

**Issue by edewit** [fabric8-launcher/launcher-frontend#302]
In the new UI after selecting a "starter" cluster the UI needs to display only the missions and runtimes that run on that selected cluster.

This means the Target Environment "screen" needs to be before the mission selection.

**Comment by gastaldi** [comment]
The UX team moved the target environment step to happen after the mission selection, perhaps we could stick with this approach? Or do you feel that choosing the Target Environment should really be the first thing a user should do?

**Comment by edewit** [comment]
Don't think that is possible, because you would select a booster that you would really want to try out only to find that after you selected your cluster you have to go back and select another option.

**Comment by quintesse** [comment]
> The UX team moved the target environment step to happen after the mission selection

Personally I think they really haven't thought about it very well. Because as @edewit mentions it's too easy to select something that will be invalidated in your next step (or even more confusingly, you won't be able to select the cluster you want).

I do wish there was a way to make the cluster selection less "important" though, but I have no idea how.

**Comment by edewit** [comment]
@catrobson What do you think about this, to me it seems that switching mission-runtime selection "page" with the target environment "page" as the most viable solution WDYT?

**Comment by catrobson** [comment]
Can a user sign up for any cluster in OpenShift, or are they forced into a cluster?  If the former (which I'm hoping for), I'd prefer that we make the clusters filter out based on booster chosen rather than filtering out the missions/runtimes.  I would expect users care less about what cluster and more about the technology they are actually trying to work with in most cases.

**Comment by gastaldi** [comment]
@catrobson they can choose the starter cluster they want when signing up in manage.openshift.com. That may include Pro accounts too. 

About choosing the mission/runtimes before the cluster, I think that makes sense, however in some cases it may be frustrating that you choose for example CRUD and find out that it doesn't run in the openshift clusters that you have access (but maybe that's where we could suggest getting a Pro account) or download as a ZIP.

**Comment by quintesse** [comment]
> I think that makes sense

I'm not so sure I agree.

A user will not be aware that the booster they select might not be available for the cluster they want to run on. You'd force them to step back and select another booster. "If I can't do that why let me choose it in the first place?"

>  I would expect users care less about what cluster and more about the technology they are actually trying to work with in most cases.

@catrobson Perhaps for people just trying things out on their free start cluster that might be true (but they will only have a single cluster so there would be no choice to make anyway). But for people who have access to one or multiple pro accounts I think they know and care very much, they're paying money for it each month after all.

**Comment by mindreeper2420** [comment]
@edewit @quintesse @gastaldi does this affect OpenShift.io or the standalone Launcher experience? The reason I ask is that it was very much thought out on the order of everything, especially in context to OpenShift.io's requirements and those of the standalone Launcher, when everything was being planned and discussed. 

With this experience, the ORDER of events does not matter. It is NOT a wizard or step process - the user can enter information into any section at any time, so requiring that a section be completed before others (with the exception of the Summary section), goes against the overall architecture and design of this experience. The approach of this entire design is that we want people to be able to experiment and learn about what can or cannot be done - this gives them the freedom to do so.

Examples:
- If you select a mission or runtime, the UI knows what is compatible, and disables options that are not valid.
- If you select that you want to download your application, the UI does not show the section for connecting to GitHub (or any git provider), as that is not a valid option.

**Comment by quintesse** [comment]
@mindreeper2420 I think the design is understood and actually pretty nice. I just think that it's based on a somewhat simplified version of the actual process.

Because as you say:

> If you select a mission or runtime, the UI knows what is compatible, and disables options that are not valid.

And that actually works very nicely, so see options enable and disable in real time so the possibilities and limitations of each choice are made very obvious.

But the thing is that the inter-dependency between possible options is not limited to missions and runtimes, the cluster choice and even if you want to download or instal onlinel on a cluster affects the same list of options. (There are boosters that will only work on certain clusters and to make it even more complex there are even boosters that can _only_ be downloaded!)

So hypothetically speaking we'd need to shows missions, runtimes, download/online and clusters in a single "page" so users could be made fully aware of all the possible relations. Of course I say "hypothetical" here because we've already gotten remarks that the new missions/runtimes selection screen is pretty complex/busy, so imagine adding even more options to that ;)

I would also say that even though the current UI doesn't really force you to go through the options in a certain order it certainly presents it that way. I don't think it's obvious for the user at all that they can go back and forth between options.

**Comment by quintesse** [comment]
@mindreeper2420 also, when you ssay:

> it was very much thought out on the order of everything, especially in context to OpenShift.io's requirements and those of the standalone Launcher

I's say that it seems to us that much more thought has been given to what OpenShift.io needs than what the Launcher needs. Unfortunately the Launcher workflow is more complex in two distinct ways IMO: 1) because it needs more information (as explained in my previous message) and 2) because it needs to be as simple as possible because its users have not "bought into" an environment. They just go to the Launcher to quickly set up a project and don't want to read or learn anything and want to forget about it as soon as possible.

**Comment by edewit** [comment]
@bdellasc Yes you need to login and then you need to do an oath2 "dance" to give launch rights to the openshift cluster that you have (or you need to register for one). Then when we know what cluster you have we can show the missions and runtimes that work on that cluster.

It's not "a must" to design something completely as we could reuse the pages we have for that
![screenshot from 2018-04-26 08-59-34](https://user-images.githubusercontent.com/51133/39290658-a948e4ac-4930-11e8-8e74-093e36194b0c.png)
_login screen, before the "black" screen_
![screenshot from 2018-04-26 08-58-50](https://user-images.githubusercontent.com/51133/39290659-a96305c6-4930-11e8-8eba-cb557a4e61b4.png)
_button for the following popup when there are no clusters that we can use_
![screenshot from 2018-04-26 08-56-44](https://user-images.githubusercontent.com/51133/39290660-a97ce90a-4930-11e8-90a4-3be9d8dc45a0.png)
_popup where users press "add" to do oath2 dance to let us use that cluster on their behalf_

**Comment by bdellasc** [comment]
@gastaldi @quintesse @edewit Just realized the timeframe question was not answered? Is this addition for Summit?

**Comment by gastaldi** [comment]
@bdellasc we are aiming to use it in summit if possible, otherwise falling back to the old UI if it does not provide feature parity with what we have now
