### ISSUE TITLE
Remove "black" intro screen

### ISSUE THREAD

**Issue by edewit** [fabric8-launcher/launcher-frontend#304]
Before the user does anything he needs to name his app, this is a bit premature.

**Comment by gastaldi** [comment]
The only case where the black screen isn't necessary is when downloading a ZIP

**Comment by edewit** [comment]
@catrobson WDYT?

**Comment by edewit** [comment]
current version: https://launch.prod-preview.openshift.io/launch/new-wizard

**Comment by bdellasc** [comment]
@edewit @gastaldi - I hear your concern, but at the same time, given the issue we have around getting the clusters integrated in the design, is this really a show-stopper? Looking at the calendar and in the grand scheme of things right now, I feel like we could leave this as-is for now and revisit post-Summit.

I feel like getting effort behind getting the cluster interactions in a better state will be far more beneficial to the user than preventing them from "wasting effort (aka a few keystrokes)" on naming an application that they decide to just download. 

@catrobson

**Comment by mindreeper2420** [comment]
Something I noticed with the zip download process - right now, the application name that the user inputs (either in the overlay, name input above the step indicator or in the summary section) is carried over to the "Next Steps" page with the following:
![screen shot 2018-04-26 at 12 59 32 pm](https://user-images.githubusercontent.com/4032718/39320367-d8135b02-4951-11e8-8270-bfbadba4b6ec.png)

The name I entered is shown in the "Commands to Activate Booster", but that name is not carried over to the zip file name (I was given `booster-crud-nodejs-1524758094727.zip`, or into the `package.json` file under "name" (also listed as `booster-crud-nodejs-1524758094727`.

Ideally, wouldn the name that the user entered be carried through the entire process (overlay, Commands, Zip, package.json) so that it can be referenced easily and, if included into a git provider, correlate to the particular repository that it resides in? I was quite surprised to see that the name I entered in the application process was not the name of the zip file, or the name in the `package.json`.

**Comment by bdellasc** [comment]
Great points, @mindreeper2420 . Aren't there places in the doc as well, where we refer to the user-input name the entered in that first screen? 

Given what Adam just pointed out, I think the focus of this issue is not accurate. The overlay is needed for all cases because that name should be carried through the generated pieces one would download as part of the .ZIP sceanrio.

**Comment by bdellasc** [comment]
Here is the design Adam referenced in his comments above for the [.ZIP download instructions page](https://redhat.invisionapp.com/share/6BEZL73M7#/286892654_Title_-_RHD_Launch_-_Select_Target_Env_-ZIP-_4)

If you look at the few screens leading up to that screen, it has the left panel sections in the old order. Other than that, it should essentially be up-to-date with the changes we're making to the section order for the cluster fix.

I'm also linking to [Stacy's document](https://docs.google.com/document/d/1PRKPlg9zOgG9Eu5GZr96GCADPhPnLwZte0jkVx5q3KQ/edit?usp=sharing) with the final content for both launch experiences. Please refer to those for the content. The content for the standalone starts on page 12.
