### ISSUE TITLE
Environment variables

### ISSUE THREAD

**Issue by edewit** [fabric8-launcher/launcher-frontend#339]
we have one build for prod and pre-prod, right now environment variables are "inserted" with `sed` into the settings.json file and index.hml. We need a better / more robust way of handling this. Maybe add perl to NGINX and serve the settings like that?

**Comment by gastaldi** [comment]
Useful links: 
https://hackerbox.io/articles/dockerised-nginx-env-vars/
https://medium.com/comparethemarket/environment-configuration-with-react-nginx-2444e1f11a4c

**Comment by ia3andy** [comment]
a very interesting article which talk about different solution for this problem depending on the context with pros and cons:
https://medium.freecodecamp.org/environment-settings-in-javascript-apps-c5f9744282b6

Since we serve the html using nginx, I like this solution:
https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#injecting-data-from-the-server-into-the-page

using this in nginx:
http://nginx.org/en/docs/http/ngx_http_sub_module.html

**Comment by ia3andy** [comment]
I am going to try out the nginx filter solution and suggest a PR.

**Comment by ia3andy** [comment]
I've found a working solution, I think it's quite nice and transparent:

I added those lines in index.html
```html
<script>
    try {
      window.INIT_CONFIG = JSON.parse('__INIT_JSON_CONFIG__');
    } catch (e) {
      window.INIT_CONFIG = undefined;
      console.info("INIT_CONFIG is not set");
    }
</script>
```

the script `entrypoint.sh` then sed the __INIT_JSON_CONFIG__ with the environment variables as a json string.

Here is the new synchronous `LaunchConfig`
```ts
declare var INIT_CONFIG: object;

@Injectable()
export class LaunchConfig extends Config {
  static settings = {};

  constructor() {
    super();
    this.processInitConfig();
    this.processEnvironment();
  }

  private processInitConfig() {
    if (INIT_CONFIG) {
      console.log("INIT_CONFIG is : " + JSON.stringify(INIT_CONFIG));
      LaunchConfig.settings = Object.assign(LaunchConfig.settings, INIT_CONFIG);
    }
  }
```

- The process is really close to what we had
- We avoid a request to load settings.json
- It's transparent for dev use which can still use `process.env..`
- We don't need multiple js / images
- The sed is quite safe since it only process one variable in one small html file


If you like it, I can provide a PR tomoz?
