### ISSUE TITLE
update the red hat developer icon to the new look

### ISSUE THREAD

**Issue by edewit** [fabric8-launcher/launcher-frontend#349]
The [new icon](https://developers.redhat.com/themes/custom/rhdp/logo.svg) was presented at summit updated our theme to include this we might need to involve UXD

**Comment by catrobson** [comment]
https://github.com/redhat-developer/design-manual holds the new icons

**Comment by catrobson** [comment]
There are not.  @bdellasc is this something you could try out?

**Comment by bdellasc** [comment]
Is this change needed for an upcoming release? The reason I ask is because I just spoke with @catrobson and @tiffanynolan (who has been working extensively on the Red Hat Developers site) and we think there needs to be a conversation with the Red Hat Developers dev team. In that conversation, we need to figure out how this page gets better integrated with the newly branded site and structure to give the user a better overall experience.

**Comment by gastaldi** [comment]
@bdellasc I believe this change is required before we adopt the Beta version as the official one, we don't have a release date yet, but we'd like to have that as soon as possible :wink:

**Comment by bdellasc** [comment]
Let's figure out who makes the most sense to have in that conversation and get a brief 1/2 hour meeting pulled together. @catrobson @tiffanynolan - who do you suggest should attend?

**Comment by tiffanynolan** [comment]
Please include me and @joeschram from the RHDDX team for initial conversations/meeting and we can include others as needed.

**Comment by bdellasc** [comment]
I just sent an invite for next week to have that conversation.

**Comment by tiffanynolan** [comment]
Thanks for scheduling the meeting, @bdellasc. With everyone's schedules for the next few weeks, I think we can wrap this one up for the short term solution of changing out the logo. Since the URL looks like it remains at developers.redhat.com, I think it makes sense to just swap in the new logo. I was originally asking if the RHD logo was the right one to user here, but due to the URL, I do think the RHD logo makes sense. We added a specific version to the [design manual](https://github.com/redhat-developer/design-manual) for Full Logo Full-Color (black background) so please use that one. 

We can talk about some longer term strategy about how to possibly separate out the "marketing" content from the App at a later date (hopefully in the June 20 meeting).

**Comment by gastaldi** [comment]
Thanks @tiffanynolan, that should work for now :wink:
