### ISSUE TITLE
Suggest going to manage.openshift.com if no clusters are found

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launcher/launcher-frontend#498]
Now with the backend integrated with manage.openshift.com (https://github.com/fabric8-launcher/launcher-backend/blob/master/services/openshift-service-impl/src/main/java/io/fabric8/launcher/service/openshift/impl/OpenShiftClusterRegistryImpl.java#L97), there would be cases where no cluster is returned in the Target Deployment step (indicating that the user didn't sign up for a starter cluster or their access was revoked). 

It would be nice to display a message/link to manage.openshift.com when this happens, but probably needs some input from the UX team first

**Comment by gastaldi** [comment]
@bdellasc any hints here?

**Comment by bdellasc** [comment]
Off the top of my head, I'd think we could treat the "Target Environment" title in the left panel the same as other incomplete/error situations where we use the x in the circle, like I suggested in [this story](https://github.com/fabric8-launcher/ngx-launcher/issues/209). 

We could also surface an appropriate inline message in the content area for the "Target Environment" section that includes the link to manage.openshift.com? Does that make sense? If so, we should probably loop Stacy in for help with the error wording.

CC @catrobson

**Comment by catrobson** [comment]
@bdellasc @gastaldi Can I get some clarity on intent?  Are we saying that the user has two use cases:

1. The user has a list of OpenShift Online clusters they can use as an OpenShift deployment target because they have already signed up, and we show them the clusters they can choose as deployment targets.

2.  The user hasn't yet registered for OpenShift Online, or they had access revoked for some reason, and we need to inform the user that in order to select a deployment target, they must register first.

If I'm understanding this correctly, I don't think your solution makes sense @bdellasc - I don't think we want to say this is an error situation - its an alternative use case the user could experience given their OpenShift Account status that we would want to handle without throwing errors I would expect - and tell them that they need to complete some more steps to see deployment targets (and give them instruction or links to do so).  Am I missing something?

**Comment by gastaldi** [comment]
@crobson yes, that's exactly the scenario we're facing. I also agree with you that this does not seem to be an error situation, I'd expect a behavior similar to the used in the GitHub step (click a link that opens manage.openshift.com and somehow redirects back to launcher - maybe in a popup).

**Comment by sherl0cks** [comment]
@catrobson I just hit this in https://github.com/fabric8-launcher/launcher-planning/issues/169#issuecomment-402269245. You are correct that this is not an error scenario, but rather alternate path that requires the user to take a few additional steps outside launch (setup an online cluster etc) before they can proceed with the initial workflow.
