### ISSUE TITLE
Improve user xp on zip/pro mission selection 

### ISSUE THREAD

**Issue by ia3andy** [fabric8-launcher/launcher-frontend#587]
We have a lot of missions and that is AWESOME!! But I think we are not giving them enough respect by showing them like that.. They take too much space and it's a pain to scroll back and forth in order to select what we want. We need to find a way to make the mission selection a great experience for the user:

![image](https://user-images.githubusercontent.com/2223984/42263166-7e500424-7f6d-11e8-8d67-8aed256f7e6f.png)

@edewit @quintesse @ALRubinger @gastaldi We need some ideas to make it better..

**Comment by ia3andy** [comment]
Hi @bdellasc, I think you could help us here?

**Comment by ia3andy** [comment]
We could show 2/3 missions boxes per line (and reduce a bit the runtimes width). 

I think it would solve the problem for a while.

**Comment by ia3andy** [comment]
Something like this:
![image](https://user-images.githubusercontent.com/2223984/42264808-01cd1216-7f72-11e8-8d79-98438ba64411.png)

**Comment by edewit** [comment]
Another possibility is to 'lock' the runtime selection column so when one scrolls down to see more missions the runimes stay in view

**Comment by quintesse** [comment]
![launcher mission_runtime idea](https://user-images.githubusercontent.com/778793/42267544-928272f4-7f79-11e8-96ba-cb2c7c5da8ab.png)

This is another idea. Because I've been starting to wonder why we give so much attention to the runtimes anyway. It started as a good way to show how missions and runtimes are linked and to make it obvious that not all combinations are available.

But I think we could just have a list of missions (or a store, I don't care so much about how the list is shown) but with a simple filter above it. Just like choosing your "department" in Amazon. EIther you don't filter and you select a mission and you select the runtime there or you already know what runtime you want and filter it from the top.

**Comment by quintesse** [comment]
![launcher mission_runtime idea v2](https://user-images.githubusercontent.com/778793/42268929-13dd59f6-7f7d-11e8-83a4-85d0c171b041.png)

I slightly different idea with bigger buttons for the Runtimes so we still give them a "premium" spot on the UI.

They would still function as a filter. So (de)selecting those buttons only affects the list of missions, never the other way around. If you've selected a missions and then select a runtime that doesn't support that mission you're selection is lost.

We would need to make it obvious to the user that the buttons are deselectable or add a "clear filter" kind of option.

**Comment by gastaldi** [comment]
@crobson @bdellasc can you point the person in UX that can help us with that?  Thank you!

**Comment by quintesse** [comment]
![launcher mission_runtime idea v3](https://user-images.githubusercontent.com/778793/42270578-8612723c-7f81-11e8-8e7f-1206fa1701de.png)

Idea 3 is the simplest. It goes back to the original design but applying the idea of a filter as introduced by my first idea.

**Comment by ia3andy** [comment]
@ALRubinger what is the status on this? Is this a GO GO?

**Comment by ia3andy** [comment]
Closed because a new react based frontend is now available.
